system:
  threads: 20
  tcp_timeout: 4.0
  http_timeout: 25.0
  user_agent: "v2rayNG/1.8.5"

checking:
  connectivity_urls:
    - "http://cp.cloudflare.com/"
    - "http://www.gstatic.com/generate_204"
  
  speedtest_url: "http://speed.cloudflare.com/__down?bytes=5000000" # 5 MB (Стандарт)
  champion_test_url: "http://speed.cloudflare.com/__down?bytes=25000000" # 25 MB (Чемпион)
  
  min_speed: 2.5
  champion_speed: 8.0
  geo_api: "https://ipwho.is/"

app:
  public_url: "https://sunny-areral.vercel.app"
  app_title: "SunnyAreral Premium"
  template_path: "config/template.html"
